[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/login.html"
  status = 302
  conditions = {Role = ["anonymous"]}

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "*.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"
